targets:
  $default:
    builders:
      equatable_gen:
        enabled: true
        options:
          auto_include: true
      json_serializable:
        options:
          field_rename: snake
      copy_with_extension_gen:
        enabled: true
